# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
      ./configuration.nix
    ];

  services.journald.extraConfig = "SystemMaxUse=1G";

  networking.extraHosts =
  ''
  127.0.0.1   localhost
  ::1         localhost
  127.0.0.2   desktopcasa
  ::1         desktopcasa
  192.168.201.200            gitlab.dev.circletouch.eu
  '';

  networking.hostName = "desktopcasa"; # Define your hostname.  


  networking.networkmanager.wifi.backend = "iwd";
  networking.networkmanager.plugins = with pkgs; [
    # Explicitly list all needed plugins, including openconnect
    networkmanager-openconnect
    # Add other plugins you might need, e.g., "openvpn", "l2tp"
  ];

  networking.wireless.iwd.enable = true;
  networking.firewall = {
    enable = true;
    allowedTCPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
    ];
    allowedUDPPortRanges = [
      { from = 1714; to = 1764; } # KDE Connect
    ];
  };



  # Bootloader.
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;
  boot.supportedFilesystems = [ "ntfs" ];
  boot.kernelModules = ["btusb" "kvm-intel"];
  boot.kernelParams = [ "btusb.enable_autosuspend=0" ];
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.extraModulePackages = [ ];


   services.restic.backups = {
    localbackup = {
      initialize = true;
      passwordFile = "/home/gasdia73/Documents/.restic";
      paths = [
          "/etc/group"
          "/etc/machine-id"
          "/etc/NetworkManager/system-connections"
          "/etc/passwd"
          "/etc/subgid"
          "/home"
          "/root"
          "/var/lib"
      ];
      repository = "/mnt/backup/restic-repo";
      timerConfig = {
        OnCalendar = "13:00";
      };
      pruneOpts = [
        "--keep-last 7"
      ];
    };
  };

  # ------------nvidia stuff----

# Enable OpenGL
  hardware.graphics = {
    enable = true;
  };
# Load nvidia driver for Xorg and Wayland
  services.xserver.videoDrivers = ["nvidia"];

  hardware.nvidia.modesetting.enable = true;
# # Nvidia power management. Experimental, and can cause sleep/suspend to fail.
#     # Enable this if you have graphical corruption issues or application crashes after waking
#     # up from sleep. This fixes it by saving the entire VRAM memory to /tmp/ instead
#     # of just the bare essentials.
  hardware.nvidia.powerManagement.enable = false;
# # Fine-grained power management. Turns off GPU when not in use.
#     # Experimental and only works on modern Nvidia GPUs (Turing or newer).
  hardware.nvidia.powerManagement.finegrained = false;
# # Use the NVidia open source kernel module (not to be confused with the
#     # independent third-party "nouveau" open source driver).
#     # Support is limited to the Turing and later architectures. Full list of
#     # supported GPUs is at:
#     # https://github.com/NVIDIA/open-gpu-kernel-modules#compatible-gpus
#     # Only available from driver 515.43.04+
#     # Currently alpha-quality/buggy, so false is currently the recommended setting.
  hardware.nvidia.open = false;
# # Enable the Nvidia settings menu,
# 	# accessible via `nvidia-settings`.
  hardware.nvidia.nvidiaSettings = true;
# # Optionally, you may need to select the appropriate driver version for your specific GPU.
  hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.latest;





  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5f54528d-0351-4563-8354-d5a036aa1ff2";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3A06-2430";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/mnt/backup" =
    { device = "/dev/disk/by-uuid/907294bd-7e64-424a-b335-41b5e58df1db";
      fsType = "ext4";
    };

  fileSystems."/mnt/extrastorage" =
    { device = "/dev/disk/by-uuid/bd4121cc-e6d5-4b80-bcda-743c6e7399df";
      fsType = "ext4";
    };       


  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno2.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
